### ISSUE TITLE
Silent's Gems

### ISSUE THREAD

**Issue by Quostin** [Y0ungSandwich/Mech-Magic-1.12.2#14]
It seems that Silent Gems tools aren't being made like that are supposed to and just being made as a "Gem Tool." When you put the item in your inventory, it completely randomized the tool you are making that has no connection to the materials you are using.
![image](https://user-images.githubusercontent.com/13752478/33226708-da2155f6-d161-11e7-9c04-5340594014aa.png)
Is the tool and toolbar for it... and when I pull it out and put it in the inventory....

![image](https://user-images.githubusercontent.com/13752478/33226711-06a9844a-d162-11e7-919d-9786a8bb7e8e.png)
It makes that. I used aquamarine and iron toolrods. I also used Agate. I think the only tool that works right is the ruby as this is also the only gem that able to make the Silent's Gems Manual

**Comment by Y0ungSandwich** [comment]
May be related to https://github.com/Y0ungSandwich/Mech-Magic-1.12.2/issues/12

**Comment by Quostin** [comment]
Interestingly, if you use a crafting bench instead of the inventory crafting bench, you will get what you put into it. At least it worked once for me.

**Comment by Y0ungSandwich** [comment]
I believe this is fixed in my newest dev version. I reproduced your recipe and got what I should. Please double check when you see the next update out.

**Comment by Quostin** [comment]
I tested it in creative world too, and it still the same problem. So it not a server config.

ME crafting station works. Creation Station works. Crafting Table works. Crafting table on a stick works.

Workbench doesn't work. Inventory Crafting Table doesn't work.

Also, you still can only use rubies to make the silent's gems manual.

**Comment by Y0ungSandwich** [comment]
Silent Gem's tools not correctly craftable in:
Cyclic Workbench
Cyclic Inventory Crafting Table

No other mods you have noticed?

**Comment by Quostin** [comment]
Nope. That is all so far. I don't know all the crafting tables types out there yet though. I am reading that Cyclic is having problems with Silent's gems, but it supposedly fixed, but your modpack still got it, even though silent's gems are on the right version that 'fixed' it.

**Comment by Y0ungSandwich** [comment]
Fixed?

**Comment by Quostin** [comment]
I haven't test it. Will do that now. Yep... All good. Silent's gems books are working now also!
